data(iris)
names(iris)
plot(iris$Petal.Width, iris$Sepal.Width, pch = 19, col = as.numeric(iris$Species))
legend(1, 4.5, legend = unique(iris$Species), col = unique(as.numeric(iris$Species)), pch = 19)
library(tree)
treel <- tree(Species ~ Sepal.Width + Petal.Width, data=iris)
summary(treel)
plot(treel)
text(treel)
plot(iris$Petal.Width, iris$Sepal.Width, pch = 19, col=as.numeric(iris$Species))
partition.tree(treel, label = "Species", add=TRUE)
legend(1.75, 4.5, legend = unique(iris$Species), col = unique(as.numeric(iris$Species)), pch = 19)
set.seed(32313)
newdata <- data.frame(Petal.Width = runif(20,0,2.5), Sepal.Width = runif(20,2,4.5))
pred1 <- predict(treel, newdata)
pred1
pred1 <- predict(treel, newdata, type="class")
plot(newdata$Petal.Width, newdata$Sepal.Width, col=as.numeric(pred1), pch=19)
partition.tree(treel, "Species", add = TRUE)
data(Cars93, package="MASS")
head(Cars93)
treeCars <- tree(DriveTrain ~ MPG.city + AirBags + EngineSize + Width + Length + Weight + Price + Cylinders + Horsepower + Wheelbase, data = Cars93)
plot(treeCars)
text(treeCars)
par(mfrow=c(1,2))
plot(cv.tree(treeCars, FUN=prune.tree, method = "misclass"))
plot(cv.tree(treeCars))
pruneTree <- prune.tree(treeCars, best=4)
plot(pruneTree)
text(pruneTree)
table(Cars93$DriveTrain, predict(pruneTree, type = "class"))
table(Cars93$DriveTrain, predict(treeCars, type = "class"))
